### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by LazerPlatypus** [saudiqbal/SaudsGoogleDomainsDynamicDNSUpdater#2]
A few little features that I think would make this application perfect!
1.) Option to start with windows. This can be manually done (and anyone that needs to update a DDNS record will already know how, but it would be nice to have)
2.) Option to start Minimized
3.) Option to "Set" (Update/Apply settings) on launch.

This would allow for the app to be installed, configured, then basically forgot about.

**Comment by saudiqbal** [comment]
All the options are already there in the file menu.
