### ISSUE TITLE
Updater does not update dual stack addresses. 

### ISSUE THREAD

**Issue by gjdunga** [saudiqbal/SaudsGoogleDomainsDynamicDNSUpdater#3]
Hello! 
How can I use this program to update both IPv4 and IPv6.  It currently is only updating for IPv6.

**Comment by saudiqbal** [comment]
Google domains does not support dual stack Internet. You can either use IPv4 or IPv6 at any given time. Until Google domains supports dual stack there is nothing can be done.

**Comment by gjdunga** [comment]
Thank you... A Trouble Ticket with Google to get this dual-stack has been created.  Trouble Ticket: 0-4213000031163
