### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by RIKWEBB** [saudiqbal/SaudsGoogleDomainsDynamicDNSUpdater#5]
Would it be possible to add an ability to update multiple Domains. I have three with Google.
As only one instance can be run, I cannot get around the problem by running more instances of the app.

Kind regards
Rik

**Comment by saudiqbal** [comment]
I will try to compile a new build without one instance limit sometime later this week.

**Comment by RIKWEBB** [comment]
Excellent - thanks :)

**Comment by saudiqbal** [comment]
Try this, I am not sure if it is working or not. https://github.com/saudiqbal/SaudsGoogleDomainsDynamicDNSUpdater/blob/master/multiDNSUpdater.exe

**Comment by RIKWEBB** [comment]
> Try this, I am not sure if it working or not. https://github.com/saudiqbal/SaudsGoogleDomainsDynamicDNSUpdater/blob/master/multiDNSUpdater.exe

Super :) 
So long as you put each .exe in a separate folder, works well. It even works with both set to 'Start with Windows' = 'Enabled'
I suppose the only enhancement would be if you could add multiple entries into the one application. However, what you have provided works for me.
Many Thanks
